services:
  block10-db:
    image: block10-db
    container_name: block10-db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - ./db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    networks:
      - app-network
  block10-server:
    depends_on:
      - block10-db
    image: block10-server
    container_name: block10-server
    ports:
      - "${SERVER_PORT}:3000"
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_HOST=block10-db
      - CLIENT_HOST=localhost
      - CLIENT_PORT=${CLIENT_PORT}
    networks:
      - app-network
  block10-client:
    depends_on:
      - block10-server
    image: block10-client
    container_name: block10-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:4173"
    environment:
      - API_HOST=localhost
      - API_PORT=${SERVER_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
